version: '3.6'

services:

  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - 5002:5000
    environment:
      - MONGODB_HOST=web-mongo
      - PYTHONUNBUFFERED=0
      - APP_NAME=${APP_NAME}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - APP_SETTINGS=${APP_SETTINGS}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_PORT=${MONGODB_PORT}
      - TWTR_CONSUMER_KEY=${TWTR_CONSUMER_KEY}
      - TWTR_CONSUMER_SECRET=${TWTR_CONSUMER_SECRET}
      - TWTR_TOKEN_KEY=${TWTR_TOKEN_KEY}
      - TWTR_TOKEN_SECRET=${TWTR_TOKEN_SECRET}
      - QUANDL_KEY=${QUANDL_KEY}
      - S3_BUCKET= ${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - WEB_DOMAIN=${WEB_DOMAIN}
    depends_on:
      - web-db
      - web-jupyterlab
      - web-jupyterhub

  web-db:
    container_name: web-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./backup_data/postgresql:/var/lib/postgresql/data"

  web-mongo:
    container_name: web-mongo
    build:
      context: ./project/server/db_mongo
      dockerfile: Dockerfile
    ports:
      - 27017:27017

  web-nginx:
    container_name: web-nginx
    build:
      context: ./project/nginx
      dockerfile: Dockerfile
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./project/nginx/conf.d:/etc/nginx/conf.d"
      - "./ssl/live:/etc/letsencrypt/live"
      - "./ssl/archive:/etc/letsencrypt/archive"

  web-jupyterlab:
    container_name: web-jupyterlab
    build:
      context: project/jupyterlab
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: >
      sh -c "jupyter lab --ip=0.0.0.0 --allow-root"
    volumes:
      - "./backup_data/web-jupyterlab/jupyter:/opt/app/data"
      - "./jupyter_tokens:/root/.local/share/jupyter/runtime/"

  web-jupyterhub:
    container_name: web-jupyterhub
    build:
      context: ./project/jupyterhub
      dockerfile: Dockerfile
    environment:
      - JUPYTERHUB_ADMIN=${JUPYTERHUB_ADMIN}
      - JUPYTERHUB_PASSWORD=${JUPYTERHUB_PASSWORD}
      - JUPYTERHUB_DUMMY_PASSWORD=${JUPYTERHUB_DUMMY_PASSWORD}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - GITHUB_HTTP=TRUE
    ports:
      - 8000:8000
    command: >
      bash -c "pip install oauthenticator &&
               jupyterhub -f /etc/jupyterhub/jupyterhub_config.py"
    volumes:
      - "./backup_data/web-jupyterhub/srv/jupyterhub:/srv/jupyterhub"
      - "./backup_data/web-jupyterhub/etc/jupyterhub:/etc/jupyterhub"
      - "./backup_data/web-jupyterhub/var/log:/var/log"
      - "./project/jupyterhub/config/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py"