FROM jupyterhub/jupyterhub:latest

#COPY ./requirements.txt ./requirements.txt

#RUN pip install oauthenticator

#COPY ./config/jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

EXPOSE 8000

#ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0", "--allow-root"]